# Generated by Django 4.0.4 on 2022-12-23 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QRCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recodr_category', models.CharField(choices=[('FOOD', 'Food'), ('UBICATION', 'Ubicaction')], max_length=100)),
            ],
            options={
                'verbose_name': 'QRCategory',
                'verbose_name_plural': 'QRCategories',
            },
        ),
        migrations.CreateModel(
            name='QRrecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('qr_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QRrecord.qrcategory')),
            ],
            options={
                'verbose_name': 'QRrecord',
                'verbose_name_plural': 'QRrecords',
            },
        ),
    ]
