# Generated by Django 4.0.4 on 2023-01-27 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QRCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'QRCategory',
                'verbose_name_plural': 'QRCategories',
            },
        ),
        migrations.CreateModel(
            name='QRrecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('qr_category', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='QRrecord.qrcategory')),
            ],
            options={
                'verbose_name': 'QRrecord',
                'verbose_name_plural': 'QRrecords',
            },
        ),
    ]
