# Generated by Django 4.0.4 on 2022-12-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRrecord', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcategory',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
