# Generated by Django 4.0.4 on 2022-12-26 20:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('QRrecord', '0003_qrcategory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcategory',
            name='recodr_category',
        ),
        migrations.RemoveField(
            model_name='qrrecord',
            name='user_id',
        ),
        migrations.AddField(
            model_name='qrcategory',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qrrecord',
            name='qr_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='QRrecord.qrcategory'),
        ),
    ]
