# Generated by Django 4.0.4 on 2022-12-28 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QRrecord', '0004_remove_qrcategory_recodr_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
