# Generated by Django 4.0.4 on 2022-12-23 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('REVIEW', 'Review'), ('COMMENTS', 'Comments'), ('SUGGESTIONS', 'suggestions'), ('BAD SERVICE', 'Bad Service'), ('COMPLAINTS', 'Complaints ')], max_length=100)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('opinion_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opinion.category')),
            ],
            options={
                'verbose_name': 'Opinion',
                'verbose_name_plural': 'Opinions',
            },
        ),
    ]
