# Generated by Django 4.0.4 on 2022-12-26 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinion', '0003_remove_category_category_alter_opinion_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='BAD_SERVICE',
            field=models.CharField(default='Bad Service', max_length=30),
        ),
        migrations.AddField(
            model_name='category',
            name='COMMENTS',
            field=models.CharField(default='Comments', max_length=30),
        ),
        migrations.AddField(
            model_name='category',
            name='COMPLAINTS',
            field=models.CharField(default='Complaints ', max_length=30),
        ),
        migrations.AddField(
            model_name='category',
            name='REVIEW',
            field=models.CharField(default='Review', max_length=30),
        ),
        migrations.AddField(
            model_name='category',
            name='SUGGESTIONS',
            field=models.CharField(default='suggestions', max_length=30),
        ),
    ]
