# Generated by Django 4.0.4 on 2022-12-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinion', '0004_category_bad_service_category_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='BAD_SERVICE',
        ),
        migrations.RemoveField(
            model_name='category',
            name='COMMENTS',
        ),
        migrations.RemoveField(
            model_name='category',
            name='COMPLAINTS',
        ),
        migrations.RemoveField(
            model_name='category',
            name='REVIEW',
        ),
        migrations.RemoveField(
            model_name='category',
            name='SUGGESTIONS',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
