# Generated by Django 4.0.4 on 2022-12-26 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('opinion', '0005_remove_category_bad_service_remove_category_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='opinion_category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='opinion.category'),
        ),
    ]
