# Generated by Django 4.0.4 on 2022-12-26 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinion', '0006_alter_opinion_opinion_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Comments', max_length=50),
        ),
    ]
