# Generated by Django 4.0.4 on 2022-12-26 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opinion', '0007_alter_category_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='name_category',
        ),
    ]
